# note: to install, run `pre-commit install`
# note: if you update this file, run `pre-commit autoupdate`
default_language_version:
    python: python3.11
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format