[tool.ruff]
line-length = 120
extend-include = ["*.ipynb"]

[tool.ruff.format]
# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
docstring-code-format = true

[tool.ruff.lint.isort]
known-local-folder = ["rd_utils"]
known-first-party=["rd_utils"]
